FROM jupyter/base-notebook
WORKDIR /code
COPY . /code/
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install 
# Install dependencies from requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8888
CMD [ "poetry", "RUN", "jupyter", "notebook", "--ip=0.0.0.0.0","--port=8888", "--no-browser", "--allow-root"]
